version: "2"
services:
  web:
    image: nginx:alpine
    ports:
      - "8993:443"
      - "8990:80"
    volumes:
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
    links:
      - app
  postgres:
    image: postgres:alpine
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fincalc
      - POSTGRES_USER=fincalc
      - POSTGRES_PASSWORD=fincalc
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  app:
    build:
      context: ./app/
      dockerfile: ./Dockerfile
    ports:
      - "8997:8997"
    command:
        - /bin/bash
        - -c
        - |
            cd /opt/app
            chmod +x ./tools/wait-for-it.sh
            /bin/bash ./tools/wait-for-it.sh -h postgres -p 5432
            /bin/bash ./tools/wait-for-it.sh -h redis -p 6379
            knex migrate:latest
            pm2-docker start app-startup.json
    volumes:
      - ./app:/opt/app
      - thevoid:/opt/app/node_modules
    environment:
      - NODE_ENV=production
      - NODE_CONFIG_DIR=./build/config
      - NODE_DEBUG_PORT=8997
    links:
      - postgres
      - redis
    depends_on:
        - postgres
volumes:
  thevoid:
  pgdata:
  redisdata:
